on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 25
          - java: 17
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: ${{matrix.java}}
        distribution: zulu
    - uses: actions/checkout@v6
    - uses: sbt/setup-sbt@2e222825582620cc38d2a54e674f3c01b7c14f5d # v1.1.24
    - run: sbt -v Test/compile
    - run: sbt -v test
